# Generated by Django 6.0.3 on 2026-04-01 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prevision', models.DateTimeField()),
                ('prix_predit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('intervalle_bas', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('intervalle_haut', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsions', to='core.marche')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsions', to='core.produit')),
            ],
        ),
        migrations.CreateModel(
            name='RelevePrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_releve', models.DateTimeField()),
                ('commentaire', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente'), ('VALIDE', 'Valide'), ('REJETE', 'Rejete')], default='EN_ATTENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collecteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releves_saisis', to=settings.AUTH_USER_MODEL)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releves', to='core.marche')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releves', to='core.produit')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationReleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('VALIDE', 'Valide'), ('REJETE', 'Rejete')], max_length=10)),
                ('motif', models.TextField(blank=True)),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validations_effectuees', to=settings.AUTH_USER_MODEL)),
                ('releve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='pricing.releveprix')),
            ],
        ),
    ]
