# Generated by Django 6.0.3 on 2026-04-01 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('adresse_livraison', models.CharField(blank=True, max_length=255)),
                ('mode_reception', models.CharField(choices=[('LIVRAISON', 'Livraison'), ('RETRAIT', 'Retrait')], default='LIVRAISON', max_length=20)),
                ('date_expedition', models.DateTimeField(blank=True, null=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmee'), ('EN_COURS', 'En cours'), ('LIVREE', 'Livree'), ('ANNULEE', 'Annulee')], default='EN_ATTENTE', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_passees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='orders.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='core.produit')),
            ],
        ),
        migrations.CreateModel(
            name='OffreVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantite_totale', models.FloatField()),
                ('quantite_disponible', models.FloatField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('date_limite', models.DateTimeField(blank=True, null=True)),
                ('mode_livraison', models.CharField(blank=True, max_length=120)),
                ('statut', models.CharField(default='ACTIVE', max_length=30)),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offres_publiees', to=settings.AUTH_USER_MODEL)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offres', to='core.marche')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offres', to='core.produit')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='orders.offrevente'),
        ),
        migrations.CreateModel(
            name='SuiviStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('ancien_statut', models.CharField(blank=True, max_length=30)),
                ('nouveau_statut', models.CharField(max_length=30)),
                ('raison', models.TextField(blank=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_statuts', to='orders.commande')),
                ('utilisateur_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modifications_statut', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
