# Generated by Django 6.0.3 on 2026-04-01 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seuil_haut', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('seuil_bas', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('canal', models.CharField(choices=[('APP', 'Application'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], default='APP', max_length=20)),
                ('frequence', models.CharField(default='QUOTIDIEN', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to=settings.AUTH_USER_MODEL)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='core.marche')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='core.produit')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueAlerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_au_moment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type_declenchement', models.CharField(choices=[('SEUIL_HAUT', 'Seuil haut'), ('SEUIL_BAS', 'Seuil bas')], max_length=20)),
                ('date_declenchement', models.DateTimeField(auto_now_add=True)),
                ('action_utilisateur', models.CharField(blank=True, max_length=120)),
                ('date_action', models.DateTimeField(blank=True, null=True)),
                ('alerte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='alerts.alerte')),
            ],
        ),
    ]
